### ISSUE TITLE
Generate certificates from within the tool

### ISSUE THREAD

**Issue by LuisMayo** [SkelXton/VHS-Redirector-Scripts#1]
Currently and while we're still using the hosts redirection method, the server requires a valid certificate issued for vhsgame.com.

If this tool was able to generate this certificates on runtime it would be perfect. The development of the server component would be easier to set up. And self-hosting would be viable again so the option cold be re-introduced.

(extra points if the generated CA certificate uses the "Name Constraints Extension" for security: https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.10)

**Comment by SkelXton** [comment]
Pushing a branch with these changes (server exe still TODO)

**Comment by LuisMayo** [comment]
It's ok server exe is another issue precisely because they're different things :3

**Comment by SkelXton** [comment]
Did the thing, so yeah done
